# Linting rules for a Dart project with custom lints enabled
# Do not use the extra ruleset so that a path dependency can be used
include: package:rexios_lints/dart/core.yaml

plugins:
  rexios_lints:
    path: ../
